development:
  adapter: mysql2
  database: pog_party_dev
  pool: 5
  timeout: 5000
  username: root
  password: pass

test:
  adapter: mysql2
  database: pog_party_test
  pool: 5
  timeout: 5000
  username: root
  password: pass

production:
  adapter: postgresql
  database: pog_party_prod
  pool: 5
  timeout: 5000